{% set name = "pdir2" %}
{% set version = "0.3.4" %}
{% set hash = "67ed9b97dd9fadc6eddd5d1a088c958b5464035f1f718563f8ccf98b2c116a21" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - setuptools >=20.6.8

  run:
    - python
    - colorama  # [win]
    - enum34  # [py==27]

test:
  imports:
    - pdir

about:
  home: http://github.com/laike9m/pdir2
  license: MIT
  license_file: LICENSE
  summary: Pretty dir printing with joy
  license_family: MIT

extra:
  recipe-maintainers:
    - nicoddemus
