{% set name = "pdir2" %}
{% set version = "0.3.2" %}
{% set hash = "26d7459a5d994cedbfb3f2c2460c8e1fe3741c6db9b69791409b13563b91d5e3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - setuptools >=20.6.8

  run:
    - python
    - colorama  # [win]
    - enum34  # [py=27]

test:
  imports:
    - pdir

about:
  home: http://github.com/laike9m/pdir2
  license: MIT
  license_file: LICENSE
  summary: Pretty dir printing with joy
  license_family: MIT

extra:
  recipe-maintainers:
    - nicoddemus
