{% set name = "pdir2" %}
{% set version = "1.1.2" %}
{% set hash = "34de77cec1250e0f00a1a50c1b9252c2a1a7fe4768b8d31fb95289d9ebdde991" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pdm-pep517
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }}
    - typing-extensions
    - colorama

test:
  requires:
    - python {{ python_min }}
  imports:
    - pdir

about:
  home: http://github.com/laike9m/pdir2
  license: MIT
  license_file: LICENSE
  summary: Pretty dir printing with joy
  license_family: MIT

extra:
  recipe-maintainers:
    - nicoddemus
