{% set name = "pdir2" %}
{% set version = "1.1.1" %}
{% set hash = "e06de82af0b94764d70625fc837d02e11c85c867ae90723a61e08ecefd9d2d1f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pdm-pep517
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }}
    - typing-extensions
    - colorama

test:
  requires:
    - python {{ python_min }}
  imports:
    - pdir

about:
  home: http://github.com/laike9m/pdir2
  license: MIT
  license_file: LICENSE
  summary: Pretty dir printing with joy
  license_family: MIT

extra:
  recipe-maintainers:
    - nicoddemus
