{% set name = "pdir2" %}
{% set version = "0.3.1.post2" %}
{% set hash_type = "sha256" %}
{% set hash = "f3c08df2387e6d34f2ce22be78de9dd809fcffae96a69be733a4e99a2b5d8872" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 1000
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - colorama
    - enum34  # [py27]

test:
  imports:
    - pdir

about:
  home: http://github.com/laike9m/pdir2
  license: MIT
  license_file: LICENSE
  summary: 'Pretty dir printing with joy'
  license_family: MIT

extra:
  recipe-maintainers:
    - nicoddemus
