travis:
  secure:
    BINSTAR_TOKEN: VgNIj7Mgdq9y/fN9xkX76b1k1aPhgdIh01jQVlEoZlPifm31PqbvbUwqHTkJor7EF384EwmbUHf571MlfqslfrigeLwA+N5wF3dTFfHQqmMv1eQ54ecryksPdEYbK2hX1cRwodAbsaUonqKAWmcfvvdKkj2gHr8GsF40Or4OKDw5ndAuhsYlKmXnfPn36fxD1Nlc+eLcv/EjMorjpG/xDFfGh5dLTb3tn/UlubRO5VQEDHZ7/QsUYqzXxwvHPekwoe83/YgSlBTUf4YNy8a2XSF9HkPIJ8AK0SgSqDjdMfWRGIn7TszJ3JwKK0U0SNO5A9iSAJ1yaRMNE5XGRSZ86njCWvu6+DI0STs2SAA7UxieEWYAPPPJ17AZVZWW4zFAswuXksLKK1SzEaQTUZXmQlbshxMDOoo0EiDmptnTv2Su7DHA0eSx543x1JrE9o6NW4TH44kxxv1V3s9pRNvVoMTKDtOmxHfKMhy3h5iA/icNjlyOgONEACNsz7oFOxCnUY54aTUEml+W36NFcFd8V6UD6ejXwidZTczVgQz1G8TR+8ubBU/GNEiqlI/SF7sfhpT3zB7ryRsoydVrJsRWI+sRmZXBhGeUNgYw4jYWN2rsv/SMhUkwrs/j0JOAl6byazULOjP0yRGuAo7qNJ7ZqoKagvX2cIicbycn/ldMLmY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
